version: "3.8"
services:
  user-service:
    build:
      context: ./services/users
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_PORT=8080
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin # Username
      POSTGRES_PASSWORD:  admin # Empty password
      POSTGRES_DB: admin # Default database
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/conf.d/pg_hba.conf # Mount custom pg_hba.conf
    command: postgres -c "hba_file=/etc/postgresql/conf.d/pg_hba.conf" # Use custom pg_hba.conf
  # auth-service:
  #   build:
  #     context: ./services/auth
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - AUTH_SERVICE_PORT=8080
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
