version: "3.8"
services:
  user-service:
    build:
      context: ./services/users
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_PORT=8080
    networks:
      - app-network

  # auth-service:
  #   build:
  #     context: ./services/auth
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - AUTH_SERVICE_PORT=8080
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
