apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: kafka-service
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: kafka-service
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: confluentinc/cp-kafka:latest
          name: kafka-service
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
