apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - hba_file=/etc/postgresql/conf.d/pg_hba.conf
          env:
            - name: POSTGRES_DB
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin
            - name: POSTGRES_USER
              value: admin
          image: postgres:15
          name: postgres-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-claim0
            - mountPath: /etc/postgresql/conf.d/pg_hba.conf
              name: postgres-cm1
              subPath: pg_hba.conf
      restartPolicy: Always
      volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: postgres-claim0
        - configMap:
            items:
              - key: pg_hba.conf
                path: pg_hba.conf
            name: postgres-cm1
          name: postgres-cm1
