apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: USER_SERVICE_DB_HOST
              value: postgres
            - name: USER_SERVICE_PORT
              value: "8080"
            - name: USER_SERVICE_REDIS_URL
              value: redis:6379
            - name: USER_SERVICE_SCHEMA_PATH
              value: /app/db/schema.sql
          image: vivekajbecorp/user-service:latest
          name: user-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
